-- carts definition

-- Drop table

-- DROP TABLE carts;

CREATE TABLE carts (
	public_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	created_at timestamptz NULL DEFAULT now(),
	products json NULL,
	discounts json NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT carts_pkey PRIMARY KEY (public_id)
);