-- inventories definition

-- Drop table

-- DROP TABLE inventories;

CREATE TABLE inventories (
	public_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	created_at timestamp NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
	warehouse uuid NOT NULL,
	product uuid NOT NULL,
	quantity int4 NOT NULL DEFAULT 0,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT inventories_pkey PRIMARY KEY (public_id)
);


-- inventories foreign keys

ALTER TABLE inventories ADD CONSTRAINT inventories_product_fkey FOREIGN KEY (product) REFERENCES products(public_id);
ALTER TABLE inventories ADD CONSTRAINT inventories_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES warehouses(public_id);