-- orders definition

-- Drop table

-- DROP TABLE orders;

CREATE TABLE orders (
	public_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	created_at timestamptz NULL DEFAULT now(),
	payment json NULL,
	price json NULL,
	products json NULL,
	shop uuid NOT NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT orders_pkey PRIMARY KEY (public_id)
);


-- orders foreign keys

ALTER TABLE orders ADD CONSTRAINT orders_shop_fkey FOREIGN KEY (shop) REFERENCES shops(public_id);