-- tokens definition

-- Drop table

-- DROP TABLE tokens;

CREATE TABLE tokens (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	"token" text NOT NULL,
	"name" text NOT NULL,
	shop uuid NOT NULL,
	expire timestamptz NULL,
	CONSTRAINT tokens_pkey PRIMARY KEY (id),
	CONSTRAINT tokens_token_key UNIQUE (token)
);


-- tokens foreign keys

ALTER TABLE tokens ADD CONSTRAINT tokens_shop_fkey FOREIGN KEY (shop) REFERENCES shops(public_id);