-- users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	public_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	"name" text NULL,
	email text NULL,
	not_active bool NOT NULL DEFAULT false,
	shop uuid NULL,
	CONSTRAINT users_pkey PRIMARY KEY (public_id),
	CONSTRAINT users_system_id_key UNIQUE (public_id)
);