-- warehouses definition

-- Drop table

-- DROP TABLE warehouses;

CREATE TABLE warehouses (
	public_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	created_at timestamptz NULL DEFAULT now(),
	country text NOT NULL,
	address text NOT NULL,
	"name" text NOT NULL,
	shop uuid NOT NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT warehouses_pkey PRIMARY KEY (public_id)
);