name: Format, Lint, Test & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  FormatAndLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - run: deno fmt --check
      
      - run: deno lint
  
  test:
    needs: FormatAndLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno cache ./src/mod.ts
      
      - run: deno task test-ci
        env:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_MEILIHOST: ${{ secrets.TEST_MEILIHOST }}
          TEST_MEILIINDEX: ${{ secrets.TEST_MEILIINDEX }}
          TEST_MEILIAPIKEY: ${{ secrets.TEST_MEILIAPIKEY }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: turquoze-backend 
          entrypoint: ./src/mod.ts
          import-map: deno.json