name: Format, Lint & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  FormatAndLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - run: deno fmt --check
      
      - run: deno lint

  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: turquoze-backend 
          entrypoint: ./src/mod.ts
          import-map: deno.json