name: Format, Lint, Test & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  FormatAndLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno fmt --check

      - run: deno lint

  test:
    needs: FormatAndLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno cache ./example/mod.ts

      - run: deno task test-ci
        env:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_MEILIHOST: ${{ secrets.TEST_MEILIHOST }}
          TEST_MEILIINDEX: ${{ secrets.TEST_MEILIINDEX }}
          TEST_MEILIAPIKEY: ${{ secrets.TEST_MEILIAPIKEY }}
